In [11]:
import numpy as np

# Jumlah kota/ports
num_cities = 40

# Jumlah kendaraan
num_vehicles = 5

# Maksimum jumlah iterasi
max_iterations = 100

# Matriks jarak antara kota/ports (misalnya, digunakan angka acak dalam contoh ini)
distance_matrix = np.random.randint(10, 100, size=(num_cities, num_cities))
np.fill_diagonal(distance_matrix, 0)  # Jarak kota ke dirinya sendiri adalah 0

# Inisialisasi pheromone pada setiap jalur
pheromone_matrix = np.ones((num_cities, num_cities))

# Algoritma Koloni Semut
for iteration in range(max_iterations):
    # Simulasi pergerakan semut
    for vehicle in range(num_vehicles):
        # Inisialisasi semut di kota awal (misalnya, kota 0)
        current_city = vehicle * (num_cities // num_vehicles)
        unvisited_cities = set(range(num_cities))
        unvisited_cities.remove(current_city)

        # Inisialisasi rute kendaraan
        route = [current_city]

        # Pergi ke kota berikutnya hingga semua kota dikunjungi
        while unvisited_cities:
            next_city = min(
                unvisited_cities,
                key=lambda city: pheromone_matrix[current_city][city]
                / distance_matrix[current_city][city],
            )
            route.append(next_city)
            unvisited_cities.remove(next_city)
            current_city = next_city

        # Kembali ke kota awal untuk menutup rute kendaraan
        route.append(vehicle * (num_cities // num_vehicles))

        # Hitung total panjang rute kendaraan
        total_distance = sum(distance_matrix[route[i]][route[i + 1]] for i in range(len(route) - 1))

        # Update pheromone pada rute yang baru saja dilalui oleh kendaraan
        for i in range(len(route) - 1):
            pheromone_matrix[route[i]][route[i + 1]] += 1.0 / total_distance

    # Penguapan pheromone pada setiap jalur setelah semua kendaraan telah bergerak
    pheromone_matrix *= 0.2

# Menampilkan hasil rute untuk masing-masing kendaraan
for vehicle in range(num_vehicles):
    start_city = vehicle * (num_cities // num_vehicles)
    end_city = (vehicle + 1) * (num_cities // num_vehicles)
    print(f"Rute Kendaraan {vehicle+1}: {route[start_city:end_city+1]}")


Rute Kendaraan 1: [32, 19, 21, 2, 13, 22, 24, 39, 33]
Rute Kendaraan 2: [33, 9, 18, 6, 8, 26, 16, 20, 29]
Rute Kendaraan 3: [29, 37, 12, 25, 7, 23, 11, 4, 35]
Rute Kendaraan 4: [35, 14, 1, 30, 38, 36, 31, 10, 0]
Rute Kendaraan 5: [0, 3, 34, 17, 28, 5, 15, 27, 32]


In [5]:
distance_matrix

array([[ 0, 12, 38, ..., 99, 32, 44],
       [91,  0, 46, ..., 58, 68, 73],
       [39, 22,  0, ..., 49, 72, 65],
       ...,
       [39, 96, 95, ...,  0, 75, 53],
       [40, 45, 18, ..., 24,  0, 21],
       [94, 74, 18, ..., 19, 47,  0]])

In [ ]:
pip install ant-colony-optimization


import numpy as np
from ant_colony import AntColony

# Jumlah kendaraan
num_vehicles = 3

# Jumlah kota/ports
num_cities = 40

# Maksimum jumlah iterasi
max_iterations = 100

# Matriks jarak antara kota/ports (misalnya, digunakan angka acak dalam contoh ini)
distance_matrix = np.random.randint(10, 100, size=(num_cities, num_cities))
np.fill_diagonal(distance_matrix, 0)  # Jarak kota ke dirinya sendiri adalah 0

# Fungsi evaluasi untuk algoritma koloni semut
def evaluate_tour(tour):
    total_distance = 0
    for i in range(len(tour) - 1):
        total_distance += distance_matrix[tour[i]][tour[i + 1]]
    # Kembali ke port awal
    total_distance += distance_matrix[tour[-1]][tour[0]]
    return total_distance

# Menentukan jalur dan menerapkan algoritma koloni semut
aco = AntColony(distance_matrix, num_vehicles, num_ants=20, max_iterations=max_iterations)
best_tours = aco.run()

# Menampilkan hasil rute untuk masing-masing kendaraan
for i, tour in enumerate(best_tours):
    print(f"Rute Kendaraan {i+1}: {tour}, Total Jarak: {evaluate_tour(tour)}")


## ACO example 2

In [3]:
import numpy as np

# Parameter ACO
num_ants = 20
num_iterations = 100
alpha = 1  # Pheromone factor
beta = 3   # Heuristic factor
rho = 0.1  # Evaporation rate

num_ports = 40
num_vehicles = 5
vehicle_capacities = [100, 120, 150, 130, 110]

# Inisialisasi matriks jarak antar port (dapat diisi dengan jarak acak)
distance_matrix = np.random.randint(10, 100, size=(num_ports, num_ports))
np.fill_diagonal(distance_matrix, 0)

# Inisialisasi muatan dari setiap port (dapat diisi dengan muatan acak)
demands = np.random.randint(5, 30, size=num_ports)

# Inisialisasi pheromone
pheromone_matrix = np.ones((num_ports, num_ports))

print(demands)
print(distance_matrix)

[29 13 28  9 26 21  5  9 10 10  5 19 23  5 13 16 19 25 19 28 28 10 27 29
 29  9 16 15 28 22 21 16 24 22 12 14 26 24 21 14]
[[ 0 63 95 ... 92 25 36]
 [24  0 55 ... 37 33 43]
 [80 67  0 ... 19 26 47]
 ...
 [63 82 99 ...  0 18 26]
 [77 89 22 ... 43  0 36]
 [33 68 56 ... 44 97  0]]


IndexError: list index out of range