In [45]:
import numpy as np

# Parameter ACO
num_ants = 10
num_iterations = 50
alpha = 1  # Pheromone factor
beta = 3   # Heuristic factor
rho = 0.1  # Evaporation rate

num_ports = 10
num_vehicles = 3
vehicle_capacities = [100, 100, 100,100,100]

# Inisialisasi matriks jarak antar port (dapat diisi dengan jarak acak)
np.random.seed(0)  # Untuk reproduktibilitas
distance_matrix = np.random.randint(10, 100, size=(num_ports, num_ports))
np.fill_diagonal(distance_matrix, 0)

# Inisialisasi muatan dari setiap port (dapat diisi dengan muatan acak)
demands = np.random.randint(5, 30, size=num_ports)

# Inisialisasi pheromone
pheromone_matrix = np.ones((num_ports, num_ports))
    
print ('num_ports :',num_ports)
print ('num_vehicles :',num_vehicles)
print ('vehicle_capacities :',vehicle_capacities)
print ('distance_matrix : \n',distance_matrix)
print ('demands :',demands)
print ('current_port :', np.random.randint(num_ports))



num_ports : 10
num_vehicles : 3
vehicle_capacities : [100, 100, 100, 100, 100]
distance_matrix : 
 [[ 0 57 74 77 77 19 93 31 46 97]
 [80  0 98 22 68 75 49 97 56 98]
 [91 47  0 87 82 19 30 90 79 89]
 [57 74 92  0 59 39 29 29 24 49]
 [42 75 19 67  0 41 84 33 45 85]
 [65 38 44 10 10  0 63 15 48 27]
 [89 14 52 68 41 11  0 51 67 45]
 [21 56 92 10 24 63 22  0 94 85]
 [78 16 78 57 13 86 62 88  0 30]
 [68 33 89 23 95 58 59 79 51  0]]
demands : [ 5 10  5 22 23  9  7 21  8  7]
current_port : 0
100


In [38]:

# Algoritma ACO
for iteration in range(num_iterations):
    ant_routes = []
    
    # Construction phase
    for ant in range(num_ants):
        vehicle_remaining_capacities = list(vehicle_capacities)
        current_port = np.random.randint(num_ports)
        route = [current_port]
        #print('ant : ',ant)
        print('route : ',route)
        #print('vehicle_remaining_capacities : ',vehicle_remaining_capacities)
        
        while len(route) < num_ports and sum(demands[port] for port in route) <= vehicle_capacities[0]:
            next_port = None
            
            # Menggunakan rule probabilistik untuk memilih port berikutnya
            probabilities = []
            for port in range(num_ports):
                print('iteration port :',port)
                print ('iteration num_ports',num_ports)
                print('route : ',route)
                print('vehicle_remaining_capacities : ',vehicle_remaining_capacities)
                
                if port not in route and demands[port] <= vehicle_remaining_capacities[route[-1]]:
                    pheromone = pheromone_matrix[current_port][port]
                    distance = distance_matrix[current_port][port]
                    probability = (pheromone ** alpha) * ((1 / distance) ** beta)
                    probabilities.append((port, probability))
            
            if not probabilities:
                break
            
            probabilities = sorted(probabilities, key=lambda x: x[1], reverse=True)
            selected_port = np.random.choice([p[0] for p in probabilities])
            next_port = selected_port
            
            route.append(next_port)
            vehicle_remaining_capacities[route[-2]] -= demands[next_port]
            current_port = next_port
        
        ant_routes.append(route)
    
    # Update pheromone
    for i in range(num_ports):
        for j in range(num_ports):
            pheromone_matrix[i][j] *= (1 - rho)
    
    for route in ant_routes:
        total_distance = sum(distance_matrix[route[i]][route[i+1]] for i in range(len(route)-1))
        total_distance += distance_matrix[route[-1]][route[0]]  # Kembali ke awal
        
        for i in range(len(route)-1):
            pheromone_matrix[route[i]][route[i+1]] += 1 / total_distance


route :  [0]
iteration port : 0
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 1
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 2
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 3
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 4
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 5
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 6
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 7
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities :  [100, 100, 100, 100, 100]
iteration port : 8
iteration num_ports 10
route :  [0]
vehicle_remaining_capacities

IndexError: list index out of range

In [ ]:
# Pilih rute terbaik
best_route = min(ant_routes, key=lambda route: sum(distance_matrix[route[i]][route[i+1]] for i in range(len(route)-1)) + distance_matrix[route[-1]][route[0]])

# Tampilkan rute untuk masing-masing kendaraan
for vehicle_id in range(num_vehicles):
    vehicle_route = [port for port in best_route if demands[port] <= vehicle_capacities[vehicle_id]]
    print(f"Rute Kendaraan {vehicle_id + 1}: {vehicle_route}")

IndexError: list index out of range

In [46]:
import random
import numpy as np

# Parameter algoritma
num_ants = 20
num_ports = 10
max_ports_to_visit = 7
vehicle_capacity = 1000
pheromone_evaporation = 0.5
pheromone_deposit = 1.0
iterations = 100

# Matriks jarak antar port (asumsi sudah diketahui)
distance_matrix = [
    [0, 29, 20, 21, 16, 31, 100, 12, 4, 31],
    [29, 0, 15, 29, 28, 40, 72, 21, 29, 41],
    [20, 15, 0, 15, 14, 25, 81, 9, 23, 27],
    [21, 29, 15, 0, 4, 12, 92, 12, 25, 13],
    [16, 28, 14, 4, 0, 16, 94, 9, 20, 16],
    [31, 40, 25, 12, 16, 0, 95, 24, 36, 3],
    [100, 72, 81, 92, 94, 95, 0, 90, 101, 99],
    [12, 21, 9, 12, 9, 24, 90, 0, 15, 25],
    [4, 29, 23, 25, 20, 36, 101, 15, 0, 35],
    [31, 41, 27, 13, 16, 3, 99, 25, 35, 0]
]

# Inisialisasi pheromone awal pada setiap edge
pheromone_matrix = np.ones((num_ports, num_ports))

# Fungsi untuk memilih port berikutnya
def select_next_port(ant, allowed_ports):
    probabilities = [pheromone_matrix[ant][port] ** 2 for port in allowed_ports]
    total_pheromone = sum(probabilities)
    probabilities = [p / total_pheromone for p in probabilities]
    chosen_port = np.random.choice(allowed_ports, p=probabilities)
    return chosen_port

# Algoritma koloni semut
for _ in range(iterations):
    for ant in range(num_ants):
        current_port = 0
        visited_ports = [current_port]
        allowed_ports = list(range(1, num_ports))
        
        # Select ports to visit based on constraints
        for _ in range(max_ports_to_visit):
            if not allowed_ports:
                break
            next_port = select_next_port(current_port, allowed_ports)
            visited_ports.append(next_port)
            allowed_ports.remove(next_port)
            current_port = next_port
        
        # Complete the route by returning to the starting port
        visited_ports.append(0)
        
        # Calculate total distance and check capacity constraint
        total_distance = sum(distance_matrix[visited_ports[i]][visited_ports[i+1]] for i in range(len(visited_ports)-1))
        if total_distance <= vehicle_capacity:
            # Deposit pheromone on the route
            for i in range(len(visited_ports)-1):
                pheromone_matrix[visited_ports[i]][visited_ports[i+1]] += pheromone_deposit / total_distance
        
        # Evaporate pheromone on all edges
        pheromone_matrix *= (1.0 - pheromone_evaporation)

# Find the best route based on pheromone values
best_route = max(range(num_ports), key=lambda port: pheromone_matrix[0][port])
print("Best route:", best_route)


Best route: 3


In [47]:
import random

# Inisialisasi parameter algoritma koloni semut
num_ants = 10
num_ports = 10
max_ports_to_visit = 7
vehicle_capacity = 1000
pheromone_initial = 1.0
pheromone_evaporation = 0.1
alpha = 1
beta = 2

# Matriks jarak antar port
distance_matrix = [
    [0, 29, 20, 21, 16, 31, 100, 12, 4, 31],
    [29, 0, 15, 29, 28, 40, 72, 21, 29, 41],
    [20, 15, 0, 15, 14, 25, 81, 9, 23, 27],
    [21, 29, 15, 0, 4, 12, 92, 12, 25, 13],
    [16, 28, 14, 4, 0, 16, 94, 9, 20, 16],
    [31, 40, 25, 12, 16, 0, 95, 24, 36, 3],
    [100, 72, 81, 92, 94, 95, 0, 90, 101, 99],
    [12, 21, 9, 12, 9, 24, 90, 0, 15, 25],
    [4, 29, 23, 25, 20, 36, 101, 15, 0, 35],
    [31, 41, 27, 13, 16, 3, 99, 25, 35, 0]
]

# Inisialisasi matriks feromon
pheromone_matrix = [[pheromone_initial] * num_ports for _ in range(num_ports)]

# Inisialisasi port yang sudah dikunjungi oleh tiap semut
visited_ports = [[False] * num_ports for _ in range(num_ants)]

# Loop iterasi algoritma koloni semut
for iteration in range(100):
    # Reset port yang sudah dikunjungi oleh tiap semut
    visited_ports = [[False] * num_ports for _ in range(num_ants)]
    
    # Langkah 1: Semua semut memilih port awal secara acak
    for ant in range(num_ants):
        start_port = random.randint(0, num_ports - 1)
        visited_ports[ant][start_port] = True
        current_port = start_port
        ports_to_visit = list(range(num_ports))
        ports_to_visit.remove(current_port)
        
        # Langkah 2: Semut memilih port selanjutnya berdasarkan aturan pemilihan (pheromone dan jarak)
        for step in range(1, num_ports):
            next_port = None
            probabilities = []
            
            for port in ports_to_visit:
                pheromone = pheromone_matrix[current_port][port]
                distance = distance_matrix[current_port][port]
                if len(ports_to_visit) <= max_ports_to_visit and sum(visited_ports[ant]) <= max_ports_to_visit:
                    probability = (pheromone ** alpha) * ((1.0 / distance) ** beta)
                    probabilities.append((port, probability))
            
            total_prob = sum(p[1] for p in probabilities)
            probabilities = [(p[0], p[1] / total_prob) for p in probabilities]
            
            r = random.uniform(0, 1)
            prob_sum = 0
            for port, probability in probabilities:
                prob_sum += probability
                if r <= prob_sum:
                    next_port = port
                    break
            
            visited_ports[ant][next_port] = True
            current_port = next_port
            ports_to_visit.remove(next_port)
    
    # Langkah 3: Menghitung panjang rute tiap semut dan update pheromone
    ant_distances = []
    for ant in range(num_ants):
        total_distance = 0
        for i in range(num_ports - 1):
            from_port = [visited_ports[ant][i]]
            to_port = [visited_ports[ant][i + 1]]
            total_distance += distance_matrix[from_port][to_port]
        ant_distances.append(total_distance)
    
    # Langkah 4: Update pheromone
    for i in range(num_ports):
        for j in range(num_ports):
            pheromone_matrix[i][j] *= (1.0 - pheromone_evaporation)
            for ant in range(num_ants):
                if visited_ports[ant][i] and visited_ports[ant][j]:
                    pheromone_matrix[i][j] += (1.0 / ant_distances[ant])
    
    best_ant = min(ant_distances)
    print(f"Iteration {iteration + 1}: Best distance = {best_ant}")

# Menampilkan rute terbaik
best_ant_index = ant_distances.index(min(ant_distances))
best_route = [i for i, visited in enumerate(visited_ports[best_ant_index]) if visited]
print("Best route:", best_route)


TypeError: list indices must be integers or slices, not NoneType