In [21]:

import yfinance as yf
import math
from datetime import date, timedelta

# !pip install yfinance
KODE = 'BBNI.JK'
today_date = date.today()
td = timedelta(400)
mulai = today_date - td
print ('mulai ',mulai , 'end ',today_date)

data = yf.download(KODE, start=mulai, end = today_date)
datam = yf.download(KODE, period="max", auto_adjust=True)
df = data['Close']

df

mulai  2022-01-22 end  2023-02-26
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


Date
2022-01-24 00:00:00+07:00    7100.0
2022-01-25 00:00:00+07:00    6800.0
2022-01-26 00:00:00+07:00    7125.0
2022-01-27 00:00:00+07:00    7200.0
2022-01-28 00:00:00+07:00    7500.0
                              ...  
2023-02-20 00:00:00+07:00    9150.0
2023-02-21 00:00:00+07:00    9050.0
2023-02-22 00:00:00+07:00    8850.0
2023-02-23 00:00:00+07:00    8950.0
2023-02-24 00:00:00+07:00    8900.0
Name: Close, Length: 270, dtype: float64

In [23]:
data_close = data.filter(['Close'])
data_close.head()

Close
Date                             
2022-01-24 00:00:00+07:00  7100.0
2022-01-25 00:00:00+07:00  6800.0
2022-01-26 00:00:00+07:00  7125.0
2022-01-27 00:00:00+07:00  7200.0
2022-01-28 00:00:00+07:00  7500.0

In [24]:
#convert data to array
dataset = data_close.values
dataset

array([[7100.],
       [6800.],
       [7125.],
       [7200.],
       [7500.],
       [7325.],
       [7375.],
       [7300.],
       [7325.],
       [7375.],
       [7500.],
       [7575.],
       [7675.],
       [7700.],
       [7700.],
       [7925.],
       [7950.],
       [7900.],
       [7975.],
       [7900.],
       [7750.],
       [7925.],
       [7825.],
       [8000.],
       [7925.],
       [7775.],
       [7900.],
       [7725.],
       [7600.],
       [7775.],
       [7775.],
       [7950.],
       [8100.],
       [8075.],
       [8350.],
       [8225.],
       [8300.],
       [8075.],
       [8025.],
       [8075.],
       [8225.],
       [8225.],
       [8500.],
       [8375.],
       [8400.],
       [8250.],
       [8200.],
       [8425.],
       [8375.],
       [8150.],
       [8300.],
       [8425.],
       [8400.],
       [8425.],
       [8450.],
       [8400.],
       [8425.],
       [8400.],
       [8975.],
       [9375.],
       [9350.],
       [9500.],
       [

In [25]:
# import library yang dibutuhkan
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# definisikan fungsi untuk membuat sekuens data
def create_sequences(X, y, time_steps=1):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        Xs.append(X.iloc[i:(i + time_steps)].values)
        ys.append(y.iloc[i + time_steps])
    return np.array(Xs), np.array(ys)

# ambil data historis saham sebagai dataset
#df = pd.read_csv('data_saham.csv')

# bagi dataset menjadi data latih dan data uji
train_size = int(len(dataset) * 0.94)
train_df = dataset[:train_size]
test_df = dataset[train_size:]

print(train_df)
print(test_df)

[[7100.]
 [6800.]
 [7125.]
 [7200.]
 [7500.]
 [7325.]
 [7375.]
 [7300.]
 [7325.]
 [7375.]
 [7500.]
 [7575.]
 [7675.]
 [7700.]
 [7700.]
 [7925.]
 [7950.]
 [7900.]
 [7975.]
 [7900.]
 [7750.]
 [7925.]
 [7825.]
 [8000.]
 [7925.]
 [7775.]
 [7900.]
 [7725.]
 [7600.]
 [7775.]
 [7775.]
 [7950.]
 [8100.]
 [8075.]
 [8350.]
 [8225.]
 [8300.]
 [8075.]
 [8025.]
 [8075.]
 [8225.]
 [8225.]
 [8500.]
 [8375.]
 [8400.]
 [8250.]
 [8200.]
 [8425.]
 [8375.]
 [8150.]
 [8300.]
 [8425.]
 [8400.]
 [8425.]
 [8450.]
 [8400.]
 [8425.]
 [8400.]
 [8975.]
 [9375.]
 [9350.]
 [9500.]
 [9600.]
 [9450.]
 [9225.]
 [8825.]
 [8900.]
 [8775.]
 [8200.]
 [8250.]
 [8450.]
 [8750.]
 [8675.]
 [8775.]
 [8850.]
 [9075.]
 [8925.]
 [9200.]
 [9200.]
 [9175.]
 [8850.]
 [8950.]
 [8900.]
 [8900.]
 [9000.]
 [8675.]
 [8300.]
 [8250.]
 [8275.]
 [8275.]
 [8250.]
 [8175.]
 [8125.]
 [8450.]
 [8150.]
 [8150.]
 [8150.]
 [8050.]
 [8075.]
 [8025.]
 [7850.]
 [7850.]
 [7650.]
 [7750.]
 [7650.]
 [7600.]
 [7600.]
 [7500.]
 [7450.]
 [7225.]
 [7275.]
 

In [26]:
scaler = MinMaxScaler(feature_range =(0,1))
scaled_data = scaler.fit_transform(dataset)
scaled_data

array([[0.09677419],
       [0.        ],
       [0.10483871],
       [0.12903226],
       [0.22580645],
       [0.16935484],
       [0.18548387],
       [0.16129032],
       [0.16935484],
       [0.18548387],
       [0.22580645],
       [0.25      ],
       [0.28225806],
       [0.29032258],
       [0.29032258],
       [0.36290323],
       [0.37096774],
       [0.35483871],
       [0.37903226],
       [0.35483871],
       [0.30645161],
       [0.36290323],
       [0.33064516],
       [0.38709677],
       [0.36290323],
       [0.31451613],
       [0.35483871],
       [0.2983871 ],
       [0.25806452],
       [0.31451613],
       [0.31451613],
       [0.37096774],
       [0.41935484],
       [0.41129032],
       [0.5       ],
       [0.45967742],
       [0.48387097],
       [0.41129032],
       [0.39516129],
       [0.41129032],
       [0.45967742],
       [0.45967742],
       [0.5483871 ],
       [0.50806452],
       [0.51612903],
       [0.46774194],
       [0.4516129 ],
       [0.524

In [11]:
# import library yang dibutuhkan
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# definisikan fungsi untuk membuat sekuens data
def create_sequences(X, y, time_steps=1):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        Xs.append(X.iloc[i:(i + time_steps)].values)
        ys.append(y.iloc[i + time_steps])
    return np.array(Xs), np.array(ys)

# ambil data historis saham sebagai dataset
#df = pd.read_csv('data_saham.csv')

# bagi dataset menjadi data latih dan data uji
train_size = int(len(df) * 0.8)
train_df = df[:train_size]
test_df = df[train_size:]

print(train_df)
print(test_df)

Date
2022-01-24 00:00:00+07:00    7100.0
2022-01-25 00:00:00+07:00    6800.0
2022-01-26 00:00:00+07:00    7125.0
2022-01-27 00:00:00+07:00    7200.0
2022-01-28 00:00:00+07:00    7500.0
                              ...  
2022-12-05 00:00:00+07:00    9750.0
2022-12-06 00:00:00+07:00    9550.0
2022-12-07 00:00:00+07:00    9500.0
2022-12-08 00:00:00+07:00    9500.0
2022-12-09 00:00:00+07:00    9550.0
Name: Close, Length: 216, dtype: float64
Date
2022-12-12 00:00:00+07:00    9525.0
2022-12-13 00:00:00+07:00    9650.0
2022-12-14 00:00:00+07:00    9525.0
2022-12-15 00:00:00+07:00    9475.0
2022-12-16 00:00:00+07:00    9800.0
2022-12-19 00:00:00+07:00    9425.0
2022-12-20 00:00:00+07:00    9450.0
2022-12-21 00:00:00+07:00    9350.0
2022-12-22 00:00:00+07:00    9425.0
2022-12-23 00:00:00+07:00    9325.0
2022-12-26 00:00:00+07:00    9325.0
2022-12-27 00:00:00+07:00    9300.0
2022-12-28 00:00:00+07:00    9225.0
2022-12-29 00:00:00+07:00    9225.0
2022-12-30 00:00:00+07:00    9225.0
2023-01-02 00

In [16]:
#convert data to array
dataset = df.values
dataset

array([7100., 6800., 7125., 7200., 7500., 7325., 7375., 7300., 7325.,
       7375., 7500., 7575., 7675., 7700., 7700., 7925., 7950., 7900.,
       7975., 7900., 7750., 7925., 7825., 8000., 7925., 7775., 7900.,
       7725., 7600., 7775., 7775., 7950., 8100., 8075., 8350., 8225.,
       8300., 8075., 8025., 8075., 8225., 8225., 8500., 8375., 8400.,
       8250., 8200., 8425., 8375., 8150., 8300., 8425., 8400., 8425.,
       8450., 8400., 8425., 8400., 8975., 9375., 9350., 9500., 9600.,
       9450., 9225., 8825., 8900., 8775., 8200., 8250., 8450., 8750.,
       8675., 8775., 8850., 9075., 8925., 9200., 9200., 9175., 8850.,
       8950., 8900., 8900., 9000., 8675., 8300., 8250., 8275., 8275.,
       8250., 8175., 8125., 8450., 8150., 8150., 8150., 8050., 8075.,
       8025., 7850., 7850., 7650., 7750., 7650., 7600., 7600., 7500.,
       7450., 7225., 7275., 7275., 7325., 7300., 7675., 7725., 7700.,
       7600., 7675., 7775., 7825., 7850., 7950., 8075., 8125., 8000.,
       8250., 8250.,

In [18]:
#get the number of rows to train the model on
training_data_len = math.ceil(len(dataset)* .9)
training_data_len

243

In [19]:
scaler = MinMaxScaler(feature_range =(0,1))
scaled_data = scaler.fit_transform(dataset)
scaled_data

ValueError: Expected 2D array, got 1D array instead:
array=[7100. 6800. 7125. 7200. 7500. 7325. 7375. 7300. 7325. 7375. 7500. 7575.
 7675. 7700. 7700. 7925. 7950. 7900. 7975. 7900. 7750. 7925. 7825. 8000.
 7925. 7775. 7900. 7725. 7600. 7775. 7775. 7950. 8100. 8075. 8350. 8225.
 8300. 8075. 8025. 8075. 8225. 8225. 8500. 8375. 8400. 8250. 8200. 8425.
 8375. 8150. 8300. 8425. 8400. 8425. 8450. 8400. 8425. 8400. 8975. 9375.
 9350. 9500. 9600. 9450. 9225. 8825. 8900. 8775. 8200. 8250. 8450. 8750.
 8675. 8775. 8850. 9075. 8925. 9200. 9200. 9175. 8850. 8950. 8900. 8900.
 9000. 8675. 8300. 8250. 8275. 8275. 8250. 8175. 8125. 8450. 8150. 8150.
 8150. 8050. 8075. 8025. 7850. 7850. 7650. 7750. 7650. 7600. 7600. 7500.
 7450. 7225. 7275. 7275. 7325. 7300. 7675. 7725. 7700. 7600. 7675. 7775.
 7825. 7850. 7950. 8075. 8125. 8000. 8250. 8250. 8450. 8475. 8525. 8525.
 8550. 8575. 8650. 8500. 8300. 8300. 8300. 8275. 8300. 8200. 8425. 8525.
 8525. 8700. 8850. 8750. 8575. 8775. 8800. 8800. 8975. 8900. 9175. 8950.
 8975. 8975. 8975. 9000. 9000. 9000. 9000. 9000. 8975. 8975. 8900. 8850.
 8850. 8900. 8775. 8750. 8700. 8650. 8750. 8425. 8575. 8675. 8775. 9000.
 9000. 9350. 9425. 9225. 9350. 9325. 9400. 9400. 9250. 9300. 9275. 9275.
 9250. 9300. 9275. 9300. 9100. 9125. 9100. 9275. 9200. 9175. 9250. 9250.
 9275. 9300. 9275. 9375. 9900. 9700. 9750. 9750. 9550. 9500. 9500. 9550.
 9525. 9650. 9525. 9475. 9800. 9425. 9450. 9350. 9425. 9325. 9325. 9300.
 9225. 9225. 9225. 9225. 9275. 9175. 9000. 8900. 9000. 8725. 8500. 8600.
 8675. 8775. 8925. 8875. 8950. 9025. 9050. 9075. 9475. 9550. 9300. 9150.
 9125. 9100. 9300. 9350. 9375. 9475. 9550. 9525. 9500. 9450. 9425. 9350.
 9275. 9150. 9050. 8850. 8950. 8900.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [14]:
train_df = train_df.reshape(-1, 1)
# normalisasi data latih dan data uji

scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_df)
test_scaled = scaler.transform(test_df)

# definisikan waktu pengamatan
TIME_STEPS = 30

# buat sekuens data
X_train, y_train = create_sequences(pd.DataFrame(train_scaled), pd.DataFrame(train_scaled)[:, 0], TIME_STEPS)
X_test, y_test = create_sequences(pd.DataFrame(test_scaled), pd.DataFrame(test_scaled)[:, 0], TIME_STEPS)

AttributeError: 'Series' object has no attribute 'reshape'

In [ ]:


# definisikan model bi-LSTM
model = tf.keras.Sequential([
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2]))),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=32, return_sequences=True)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=16)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1)
])

# latih model
model.compile(loss='mse', optimizer='adam')
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1, verbose=1)

# evaluasi model
test_loss = model.evaluate(X_test, y_test)
print(f'Test loss: {test_loss}')

# membuat prediksi untuk data uji
y_pred = model.predict(X_test)

# hitung akurasi model
accuracy = np.mean(np.abs(y_pred - y_test) <
